### ISSUE TITLE
a few observations

### ISSUE THREAD

**Issue by tessus** [ThomasDaheim/ownNoteEditor#10]
First of all I wanted to mention that I am grateful that you took the time to create this app. It's the only app I found which can easily edit rich text content.

However, there are a few things I've noticed while using and testing the app over the last days:

* The memory footprint is rather large. After opening the app it uses 197 MB. When I open a note that has 3 words in it and close it, the memory consumption goes up to 235 MB. I would have assumed that the memory goes down to 197 MB again. After a while it grew to 345 MB.

* Is there a way to add a print function? In that case, it would be easy to convert a note to PDF.

* If the app is started and a note is changed on the server, the note is synced to the local file system at some point. The problem is that the app does not refresh the notes listing, nor the note, if that certain note is open.

While the first 2 items are rather trivial, the last one might be a bit more complicated to solve. There are few options how conflict resolution could be managed. I have some ideas, but I haven't written any Java code for ages. Maybe @madmas can help with this last item.

**Comment by ThomasDaheim** [comment]
Hi @tessus,

glad to see that my self-learn project is actually of use to someone :-)

I would split your remarks into separate issues since memory footprint might as well be a bug and the other points are enhancements. Will add my comments in the new issues.

**Comment by tessus** [comment]
@ThomasDaheim I didn't want to open 3 tickets at once. :-)
But I would have opened them later... but you have already done that - thanks.
Closing this one, since the other tickets have already been created.
