### ISSUE TITLE
Memory footprint

### ISSUE THREAD

**Issue by ThomasDaheim** [ThomasDaheim/ownNoteEditor#11]
Derived from #10:

> The memory footprint is rather large. After opening the app it uses 197 MB. When I open a note that has 3 words in it and close it, the memory consumption goes up to 235 MB. I would have assumed that the memory goes down to 197 MB again. After a while it grew to 345 MB.

Unfortunately, my knowledge of java and memory management is very limited. I could think of a few points that lead to that: Editor not cleaned up properly when changing note to edit, ...

**Comment by tessus** [comment]
To narrow it down: it's either a problem with the VM (or it might be normal behavior - it's Java after all) or some dealloc stuff is missing in the code. I could fix it, if it were C, but I know far too less about Java memory management.

**Comment by htrampe** [comment]
He! If i start the application one core of my cpu is 100-percent active - all the time. Also if iam offline...thats not so good for working it on a notebook ;). Fix would be good!

**Comment by ThomasDaheim** [comment]
Good catch! Thats a side-effect of issue #14 but there's a way to keep functionality and reduce CPU-load. Will include that soon.

**Comment by htrampe** [comment]
Sounds great - waiting for it :+1:

**Comment by ThomasDaheim** [comment]
Have a look at CPU-load-issue branch if that helps (works here under Win 10)

**Comment by htrampe** [comment]
YEAH! Works under Linux Ubuntu 14.04.03 too - great! This application makes make open-source-workflow perfect. More Flowers :+1:

**Comment by ThomasDaheim** [comment]
Your welcome! Luckily, I had a bit of free time on my hands. Otherwise, it would take somewhat longer to come up with a fix.

As for the memory footprint: I can't see any issues under Win10. Memory doesn't seem to increase over time - but maybe I didn't look long enough. How does it work under Ubuntu?

**Comment by htrampe** [comment]
Well, under Ubuntu one core is 100 % in work all the time - it does not depends on sync or changing. Memory-Load is hard to say - it seems that the vm of java takes normal load. Only problem is cpu-load on one core. WIth the fix it works normaly :+1: but i need to open another issue: if i change the order of groups the window-tooltip stay and does not disappears...but i need to check it on win10 too. 

I need to say one fact: You create an offline-application for ownNote and with that app u open the way to completly replace OneNote! Thats absolutly stunning so pls keep working! Iam preparing a big article in german on my website to promote that. With OwnCloud, ownNote, LaTeX, Sublime and Caldav/carddav everything is prepared to work 100%-open-source. Thats great :+1:

**Comment by ThomasDaheim** [comment]
Memory footprint constant over time under Win10, so closing this issue
