### ISSUE TITLE
Add print functionality

### ISSUE THREAD

**Issue by ThomasDaheim** [ThomasDaheim/ownNoteEditor#12]
Derived from #10:

> Is there a way to add a print function? In that case, it would be easy to convert a note to PDF.

Sounds good! Will add it to my list of enhancements.

**Comment by ThomasDaheim** [comment]
This is already supported by JavaFX 8 - https://docs.oracle.com/javase/8/javafx/api/javafx/scene/web/HTMLEditor.html#print-javafx.print.PrinterJob- So I only need to add a button somewhere in the editor.

**Comment by tessus** [comment]
Cool, I hoped this one would be an easy one.

**Comment by ThomasDaheim** [comment]
@tessus: Could you please check with latest merge?

Javafx printing feature seems to work in general for me but fails for one of my printers...

**Comment by tessus** [comment]
Yes, the print dialog shows up and I could create a PDF. :+1: 

I couldn't test printing to a real printer, since I'm still in the office and somebody forgot to change the toner.

**Comment by ThomasDaheim** [comment]
Worked for me on a real printer too. Closing this issue...
