### ISSUE TITLE
Track changes to local file system

### ISSUE THREAD

**Issue by ThomasDaheim** [ThomasDaheim/ownNoteEditor#14]
Derived from #10:

> If the app is started and a note is changed on the server, the note is synced to the local file system at some point. The problem is that the app does not refresh the notes listing, nor the note, if that certain note is open.

Manual workaround: Re-Select the path to your notes :-)

See also #13, that would be needed here as well.

**Comment by tessus** [comment]
Yes, #13 is a part of one of the conflict resolution scenarios.

The manual workaround only works, if you select a *different* path first. Just opening the file dialog and clicking `Open` doesn't do anything. I tried that the moment I stumbled upon the no-refresh issue.

**Comment by ThomasDaheim** [comment]
https://docs.oracle.com/javase/tutorial/essential/io/notification.html should help with that.

**Comment by tessus** [comment]
yes, this API looks good. The next step is to define what we want for conflict resolution.

If no note is open and something changes, the list can be refreshed.
If a note is open, there are several options:
* note has been deleted (or renamed) on the server
 * popup: note has been deleted on the server - do you want to save a local copy (save / discard)
* note has been changed on the server, but not on the client yet
 * automatically reload the note
* note has been changed on the server AND on the client
 * popup: note has been changed locally and on the server - which version do you want to use (server / local / save local as...)

This is just a preliminary list. I hope I didn't forget something. Also, there might be other ways to resolve a conflict.

**Comment by ThomasDaheim** [comment]
There are surely more elaborate ways to handle conflicts :-) But your list looks good as a start.

**Comment by ThomasDaheim** [comment]
Have added usage of this API as part of my redesign in #15.

Since it was a bit tricky to use the API (own thread for monitoring required that communicates with the single UI thread) some testing is required before I can merge the branch to create Version 2.0 of the editor.

**Comment by tessus** [comment]
I'll test the branch lookAndFeel and let you know what I find.

**Comment by tessus** [comment]
ok, a few things I have noticed so far:

* you removed the file `ownNoteEditor/src/tf/ownnote/ui/main/ownNoteEditor.icns`, which is the icons file for the macApp build step.
* there's no documentation how to use the flags to change the layout
```
./ownNoteEditor -classic
Dec 27, 2015 2:10:15 PM tf.ownnote.ui.helper.OwnNoteEditorParameters init
SEVERE: null
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -classic

./ownNoteEditor --classic
Dec 27, 2015 2:10:33 PM tf.ownnote.ui.helper.OwnNoteEditorParameters init
SEVERE: null
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --classic
```
* if you start it as an app (or double click on the jar on windows), flags are not taken into consideration. This means whatever the default is will be used. Thus you can **only** use a different layout, when you start it from the command line. I suggest to use a preference pane for changing the layout.

**Comment by ThomasDaheim** [comment]
Thanks for testing @tessus!

- `ownNoteEditor/src/tf/ownnote/ui/main/ownNoteEditor.icns`: Ooops, not sure where that got lost - have added it again
- documentation: What would be a good way to do that? Some kind of "usage info" instead of the exception maybe. Will have a look at that.
- preference pane: I have thought about that as well - is on my list of things still to add :-) Main point is that you then need to be able to switch layouts on the fly and also to store the info somewhere

**Comment by ThomasDaheim** [comment]
Have created two new issues #19 and #20 for that

**Comment by tessus** [comment]
@ThomasDaheim btw, thanks for implementing all these goodies.
