### ISSUE TITLE
Build fails under NetBeans on Win

### ISSUE THREAD

**Issue by ThomasDaheim** [ThomasDaheim/ownNoteEditor#16]
Hi @tessus,

with your update I'm now getting the following error when doing "Clean and Build" in Netbeans on WIn:

```
Executing: gradle clean build
Arguments: [-c, D:\Thomas\Development\NetBeansProjects\ownNoteEditor\ownNoteEditor\settings.gradle]

:clean
:copyBackgroundImage SKIPPED
:bundleJRE SKIPPED
:copyIcon
:copyStub
Note: D:\Thomas\Development\NetBeansProjects\ownNoteEditor\ownNoteEditor\src\tf\ownnote\ui\helper\OwnNoteEditorParameters.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Thomas\Development\NetBeansProjects\ownNoteEditor\ownNoteEditor\src\tf\ownnote\ui\main\OwnNoteEditor.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileJava
:processResources
:classes
:jar
:copyToResourcesJava
:generatePkgInfo
:generatePlist
:createApp
:createDmg FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createDmg'.
> A problem occurred starting process 'command 'hdiutil''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.79 secs



Build failure (see the Notifications window for stacktrace): gradle clean build
```

Which is true, since I don't want a Build for Mac...

**Comment by tessus** [comment]
I don't understand why NetBeans even tries to run the task `createDmg`. Or any of these tasks, because then NetBeans would go through all tasks that are returned by `./gradlew tasks` which also doesn't make any sense.

Maybe there is a setting in NetBeans that allows you to specify what tasks are run for a `Clean and Build`.

The changes I made **did not** change any default behavior. I only added additional functionality.

I have no idea why this would be happening.

**Comment by tessus** [comment]
Let me read up on gradle. Maybe you have a setting in one of the files that specifies to run all tasks.

**Comment by tessus** [comment]
I've narrowed the problem down. It seems that certain tasks are added to the action `gradlew build`.
I opened the following ticket crotwell/gradle-macappbundle#39.

**Comment by tessus** [comment]
@ThomasDaheim the new pull request should fix your problem.
