### ISSUE TITLE
Documentation: Add "usage info" that describes the flags

### ISSUE THREAD

**Issue by ThomasDaheim** [ThomasDaheim/ownNoteEditor#19]
Instead of throwing an exception in case of unrecognized flags...

**Comment by ThomasDaheim** [comment]
Added a usage info in case of unrecognized parameters - suppressed exception

**Comment by tessus** [comment]
It does show the usage info now, but the flags do not work. I always get the same look and feel (the original one).
Even, if you specify something other than classic and onenote, the editor starts with the old layout:

```
./ownNoteEditor --lookAndFeel IdontExist
Option lookAndFeel found: IdontExist
[snip]
```

**Comment by ThomasDaheim** [comment]
I'm using `--lookAndFeel="oneNote"` and that works on my end

**Comment by tessus** [comment]
yes, this works, but in that case the help text is confusing:

```
Valid options are:
 -lookAndFeel,--lookAndFeel <arg>   Layout to use - "classic" or "onenote"
```

This help text tells me that the argument is either `--lookAndFeel classic` or `--lookAndFeel onenote`.

Btw, the text also states `onenote`, which does not work either. -> case sensitivity

It should say something like:

```
Valid options are:
 -lookAndFeel,--lookAndFeel="<arg>"   Layout to use - <arg> can be "classic" or "oneNote"
```

**Comment by ThomasDaheim** [comment]
Thats why you need users to build usable software :-) Hopefully, now it works as expected

**Comment by tessus** [comment]
thanks, it works.
