### ISSUE TITLE
Add preference pane for changing the layout

### ISSUE THREAD

**Issue by ThomasDaheim** [ThomasDaheim/ownNoteEditor#20]

**Comment by tessus** [comment]
Description: If you start it as an app (or double click on the jar on windows), flags are not taken into consideration. This means whatever the default is will be used. Thus you can only use a different layout, when you start it from the command line. I suggest to use a preference pane for changing the layout.

Comment by @ThomasDaheim:
I have thought about that as well - is on my list of things still to add :-) Main point is that you then need to be able to switch layouts on the fly and also to store the info somewhere

**Comment by tessus** [comment]
> I have thought about that as well - is on my list of things still to add :-) Main point is that you then need to be able to switch layouts on the fly and also to store the info somewhere

Not necessarily. You can always add a text that states "restart required".
Also, you already store the path of the notes. Once you have selected it via the GUI, the app always starts with that path, which means it has to be stored somewhere.

**Comment by ThomasDaheim** [comment]
Have played around with this a bit. Unfortunately, you can't have a tooltip @ a menuitem in javafx - so I had to add a disabled menuitem to give the hint... (and yes, i have noticed that disabled menuitems are hard to read :-))

**Comment by tessus** [comment]
I don't understand your comment. What does it have to do with a preference pane/window?

**Comment by ThomasDaheim** [comment]
For simplicity, I have added this as a menu and not a new pane - and I wanted to show "restart required" as tooltip

**Comment by tessus** [comment]
aha. got it. thank you.
