### ISSUE TITLE
oneNote layout issue

### ISSUE THREAD

**Issue by tessus** [ThomasDaheim/ownNoteEditor#22]
when starting the editor or switching the groups via the tab the automatically selected note is almost unreadable (dark grey on black):

<img width="727" alt="screen shot 2015-12-27 at 17 07 57" src="https://cloud.githubusercontent.com/assets/223439/12012311/6e9152e4-acbc-11e5-9bde-5ab14ddfee0f.png">

then, if you hover over an already selected entry, it is also rather hard to read:

<img width="727" alt="screen shot 2015-12-27 at 17 09 57" src="https://cloud.githubusercontent.com/assets/223439/12012318/c662e820-acbc-11e5-8c06-0b89d180c4a1.png">

**Comment by ThomasDaheim** [comment]
Yes, thats the last thing on my list before release: "pimp my css" :-)

**Comment by ThomasDaheim** [comment]
Tried to improve readability a bit. Hope that helps!

**Comment by tessus** [comment]
Yes, it's a lot better. Thanks.
