### ISSUE TITLE
saving a note triggers change popup

### ISSUE THREAD

**Issue by tessus** [ThomasDaheim/ownNoteEditor#23]
After saving a note, I get the following message:

<img width="370" alt="screen shot 2015-12-27 at 17 27 45" src="https://cloud.githubusercontent.com/assets/223439/12012466/fb4216b4-acc2-11e5-9154-f3897db3b7d1.png">

This is either a timing or a locking issue. Another problem could be that it doesn't check for a difference. It should only show the popup, iff the content between the local filesystem and the current note (in memory) is different.

**Comment by ThomasDaheim** [comment]
Mmmh, I have added some delay to avoid getting triggered by my own changes. Maybe I need to extend that time period. Does that happen for all saves or just once in a while?

**Comment by tessus** [comment]
It has happened for every save. I'm not sure, if a delay is the correct way to handle this. A delay may result in a race condition.

**Comment by ThomasDaheim** [comment]
Let me try to explain in more detail:

There is some delay til the watcher thread informs of changes to the file system. So only after saving changes the event from the watcher gets fired. The delay I have added is to ignore changes for a while after doing my own changes. Haven't found any other good way to interact with the watcher so far. Under Win7-10 the duration to ignore changes seems sufficient, maybe it needs to be longer for your OS.

**Comment by tessus** [comment]
The watcher has to be deactivated as soon as you press save and then re-activated when the save is complete.

**Comment by ThomasDaheim** [comment]
Tried that but then ran into other issues. I'll need to dig deeper into this. In the meantime I have extended the "ignore" time - maybe that helps til I find a proper way to handle this...

**Comment by ThomasDaheim** [comment]
Unfortunately, the Watcher implementation doesn't provide any suspend - resume mechanism (or I couldn't find it...). So I had to use brute force to handle own changes. New commit should (hopefully) handle all constellations now.

**Comment by tessus** [comment]
yes, it works. no more popup after saving note
