### ISSUE TITLE
unsaved changes dialog

### ISSUE THREAD

**Issue by tessus** [ThomasDaheim/ownNoteEditor#25]
When you click on a different note and you have unsaved changes the following popup shows up:

<img width="358" alt="screen shot 2015-12-27 at 18 44 18" src="https://cloud.githubusercontent.com/assets/223439/12012590/0b2edaf6-acca-11e5-8f0e-d162edbefd11.png">

This also has some dire consequences. There should be 3 buttons:
Yes, No (discard curent changes), Cancel

`Cancel` must not be used for `No`. `Cancel` is used for cancelling the current action. In this case it means that the dialog would disappear and the current note is still in memory and edited, but not saved.
`No` means the current changes are discarded.
`Yes` means the changes are saved.

**Comment by tessus** [comment]
P.S.: sorry to open so many issues.

**Comment by ThomasDaheim** [comment]
Fine with me! Easier to track things with many different issues than with only one big one...

**Comment by ThomasDaheim** [comment]
Have added three buttons with long write-up for such cases:

```
Options:
Save own note to different name
Save own note and overwrite file system changes
Load changed note and discard own changes
```

Hope thats clear enough now :-)

**Comment by tessus** [comment]
I think you might have mixed up #24 and #25.

This issue still persists. There's no new dialog with 3 options. I still see the same dialog as in the screenshot above https://github.com/ThomasDaheim/ownNoteEditor/issues/25#issue-124001687

**Comment by ThomasDaheim** [comment]
You're right - I shouldn't commit so late in the day :-) Will have a look at it again

**Comment by ThomasDaheim** [comment]
Hi @tessus,

unfortunately, I haven't found any way to do "Cancel" properly. It would need to stop e.g. changes tabs or notes when clicking on them. But I haven't found a way to get the related event BEFORE the focus has changed. So with "Cancel" you would end up still editing your note but the UI would e.g. show a different group with a totally different list of notes...
