### ISSUE TITLE
deleting a note does not work

### ISSUE THREAD

**Issue by tessus** [ThomasDaheim/ownNoteEditor#26]
When I delete a note via right click and then `Delete`, the note is deleted without a warning (which is not good btw).

But the problem is that it re-appears after a while. This might be a problem with the Notes app though - I will have to investigate.

**Comment by ThomasDaheim** [comment]
I hate those "do you really want to delete" popups...

**Comment by tessus** [comment]
True, I don't like them either, but in that case people have to know that there will be no warning.

**Comment by tessus** [comment]
I've opened a ticket at https://github.com/Fmstrat/ownnote/issues/264, but I believe this app is dead.
The developer hasn't been working on it for months and the list of bugs is getting longer and longer.

**Comment by ThomasDaheim** [comment]
Seems to work for me under Windows. So far I didn't have the issue that deleted notes come back to life...

**Comment by tessus** [comment]
This is not a client issue, nor depended on the OS.
Maybe it has to do with the Redis Cache on the server (I have noticed there are several issues mentioning ownNote doesn't work properly with redis cache). I also saw tickets that describe issues with oc 8.2.1, which I use.

**Comment by aviret** [comment]
It could be that the fact that the note is still in the database of ownNote, so when you connect back to the application within ownCloud, it restores the deleted files.
You have exactly the same behavior if you delete a note file from the "Files" application instead of ownNote, the note is restored back.

**Comment by aviret** [comment]
And when moving a Note to another group, if you reconnect back to ownNote in ownCloud, you will at the end have 2 Notes, because the moved one is back (restored by ownNote).

**Comment by tessus** [comment]
I've opened a ticket at Fmstrat/ownnote#264, but nothing happened so far.

**Comment by ThomasDaheim** [comment]
Again, I have never run into any problem like this. I have the Windows client for ownCloud running in the background and it immediately passes all my changes on to ownCloud...

I store my notes in "Database and Folder", I think thats the default?

**Comment by aviret** [comment]
If you make a refresh of the ownNote application in your browser, the moved or deleted notes reappear in the Note folder. I also have "Database and Folder" in the preferences. If you change the folder name, you will receive all your notes in the new folder, taken from the database.

**Comment by ThomasDaheim** [comment]
I rarely ever use the ownNote in my browser - may too slow...
