### ISSUE TITLE
Image not working

### ISSUE THREAD

**Issue by htrampe** [ThomasDaheim/ownNoteEditor#31]
Hi! Great work so far so keep it on.

I found an error with the images. If a load online an image into a note - its fine and will be shown up in the offline-editor. But if iam inserting an image in the offline-editor it will not be shown up in the online editor. So images online -> offline OK
images offline -> Online Not working!

THX!

**Comment by ThomasDaheim** [comment]
Will have a look at that, thanks for the catch

**Comment by ThomasDaheim** [comment]
Here is why: if you add an image in the offline editor only the "file" is added bit instead the "data" should be added as in the web editor. Should (hopefully) not be too hard to fix...

**Comment by ThomasDaheim** [comment]
I have added a fix in branch Issue-#31. Could you please check and verify?

Also, I tried to support the same for drag & drop but didn't succeed. The Webview in JavaFX does some complicated things that I don't want to disturb :-)

**Comment by htrampe** [comment]
Working perfect - great! THX! Now i can use it for daily business. Drag & Drop would be great but not necesarry. Did u start working to make size-changing possible? btw: great open-source-project :+1:

**Comment by ThomasDaheim** [comment]
One issue at a time :-)

Thanks for the flowers. After using other peoples open source stuff for so long I decided its time to provide something as well.
