### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by caco3** [ThomasDaheim/ownNoteEditor#35]
I was able to successfully build and run it under Linux (Ubuntu 16.04) with
 ./gradlew run 
How can I pack it into an application like documented for OS X?

Would it possible to provide such binaries directly in GitHub?

**Comment by ThomasDaheim** [comment]
Hi,

I don't really think that uploading binaries is a good idea. Anyways, the OS X support was provided by @tessus, so only he might be able to help you with any questions regarding that.

**Comment by tessus** [comment]
Hey @caco3,

You can create an application or a .dmg file by running the following commands:
`./gradlew createApp`
`./gradlew createDmg`

It is also described in the [README.md](https://github.com/ThomasDaheim/ownNoteEditor/blob/master/README.md) file.

You can even bundle a JRE with it, if you want to. Have a look at:
https://github.com/ThomasDaheim/ownNoteEditor/blob/master/ownNoteEditor/build.gradle#L22

**Comment by caco3** [comment]
Thanks for the hint.
I tried `./gradlew createApp` 
But it doesn’t create the folder `build/distributions` as suggested:
```
ls -c1 build
libs
resources
tmp
classes
dependency-cache
macApp
```
I only get an (empty) `build/distributions` when I run `./gradlew createDmg`, but that obviously fails under Linux because `hdiutil` are missing.

How ever I can see a jar file in `./build/macApp/ownNoteEditor.app/Contents/Java/`.
But when I start it with
```
cd ./build/macApp/ownNoteEditor.app/Contents/Java/
java -jar ownNoteEditor.jar 
```
I get the error `kein Hauptmanifestattribut, in ownNoteEditor.jar`

**Comment by caco3** [comment]
It looks like as if the file `MANIFEST.MF` lackes some information (i.e. main class).
But I haven’t jet figured out its correct content.

**Comment by tessus** [comment]
Ok, the 2 commands I mentioned are for Mac OSX **only**.

If you want to create a jar file or a distributable tree on Linux or Windows, you have to use gradle's other options.
e.g. `./gradlew installDist`

The tree will be in `build/install`. There are other options as well. Run `./gradlew tasks` to list them.

**Comment by caco3** [comment]
Great, thank you very much for your help!

I never used gradlew before, so wasn’t aware of those parameters.

When I run `./gradlew distZip`, I get a file `./build/distributions/ownNoteEditor.zip`
It can be unpacked and started from Linux as well as from Windows (untested).
Linux:
`./bin/ownNoteEditor`

**Comment by caco3** [comment]
@ThomasDaheim: Maybe you want to extend the README.md to contain this information.

**Comment by ThomasDaheim** [comment]
Added info on ./gradlew installDist usage
