### ISSUE TITLE
Colorize entries according to category

### ISSUE THREAD

**Issue by caco3** [ThomasDaheim/ownNoteEditor#36]
- [x] I  would suggest to give the category "All" no color.
- [ ] Instead, the entries could be marked (background color or simply a dot) with the color of their category.

**Comment by ThomasDaheim** [comment]
Hi cac03,

first part should be easy to do. Marking the Notes in the list according to their category might be more involved.

Will have a look at it...

**Comment by ThomasDaheim** [comment]
I have set the "All" to "lightgrey" - white looks a bit strange...

**Comment by caco3** [comment]
Gray looks ok to me.

**Comment by ThomasDaheim** [comment]
Have a look at pull request  UI Candy added #51 - I have added a first version of the coloring of the notes. Looks a bit strange - but at least it seems to work :-)

Also testing of the other changes in that pull request would be appreciated!

**Comment by ThomasDaheim** [comment]
Pull request for this has been merged
