### ISSUE TITLE
Add buttons

### ISSUE THREAD

**Issue by caco3** [ThomasDaheim/ownNoteEditor#37]
I would suggest to add buttons to be able to create, rename and delete notes (and categories).
Double click and right click is not always obvious.

**Comment by ThomasDaheim** [comment]
Hi caco3,

I presume you mean the "oneNote" view? For the "classic" I didn't want to deviate from the look & feel of the web UI.

**Comment by caco3** [comment]
Yes, I referred to the oneNote theme.

**Comment by ThomasDaheim** [comment]
I have now added accelerators CTRL+N/D/S. I'd rather not add buttons as well for which I need to keep track when to enable, ...
