### ISSUE TITLE
Empty categories disappear

### ISSUE THREAD

**Issue by caco3** [ThomasDaheim/ownNoteEditor#38]
When an category stays empty (contains no entries), it will disappear on the next start.

**Comment by aviret** [comment]
The categories come from the file name of the notes.
ownNote has the same behavior. If the empty categories have to be saved, and this is changed in ownNoteEditor, the idea could be to add this new feature also in ownNote, to be consistent.

**Comment by ThomasDaheim** [comment]
I don't see a way how this could be supported.

Thats how ownNote works: Categories as such do not exist - they are only stored as part of the notes filename. So without a note in a category there is no permanent storage.

Would need to check in detail but I guess that would require some "hidden" way to store categories that might break ownNote...
