### ISSUE TITLE
When a new note or category is created, directly change to the name edit mode

### ISSUE THREAD

**Issue by caco3** [ThomasDaheim/ownNoteEditor#39]
Suggestion:
When a new note or category is created, directly change to the name edit mode.

**Comment by ThomasDaheim** [comment]
Still work in progress. I manage to select the new note but I can't yet trigger editing from the code,,,

**Comment by ThomasDaheim** [comment]
Works after some struggling. Will create a pull request for "Minor enhancements" so that it can be tested.

**Comment by ThomasDaheim** [comment]
Could you please test if that works as expected?

**Comment by caco3** [comment]
Working as expected.
Thank you very much!
