### ISSUE TITLE
Wrong height of content window

### ISSUE THREAD

**Issue by caco3** [ThomasDaheim/ownNoteEditor#40]
The content window seems not to have the correct height (scrollbars don’t go all the way down to bottom):
![screenshot3](https://cloud.githubusercontent.com/assets/1783586/15268229/4c644cb0-19d8-11e6-89b6-c5449bdc2679.png)

**Comment by ThomasDaheim** [comment]
Thanks for pointing that out. Will have a look at it.

**Comment by ThomasDaheim** [comment]
So far all my ideas to fix that haven't wworked out... Might take a bit longer to resolve this :-(

**Comment by aviret** [comment]
Hello,

Did you try to play with Scenic View (see http://fxexperience.com/scenic-view/) ?
I have seen that there is a prefHeight of 600 in the WebView of the HTML Editor.
![webviewprefheight](https://cloud.githubusercontent.com/assets/12494348/15565644/5ec6e67c-231c-11e6-886a-70e209a9b10d.png)
If you set this to 700, the HTML Editor take the rest of the window.

**Comment by aviret** [comment]
So, this could be solved by setting the prefHeight to a higher value in initHTMLEditor():

`    private void initHTMLEditor() {
        mWebView = (WebView) myHTMLEditor.lookup(WEB_VIEW);
        mTopToolBar = (ToolBar) myHTMLEditor.lookup(TOP_TOOLBAR);
        mBottomToolBar = (ToolBar) myHTMLEditor.lookup(BOTTOM_TOOLBAR);

        mWebView.setPrefHeight(900);`

**Comment by ThomasDaheim** [comment]
I did bind the height of the htmleditor to the pane. But it seems it doesn't pass it on to its webview child window :-(

So I think the workaround is to go with your change.

**Comment by ThomasDaheim** [comment]
I think that https://stackoverflow.com/questions/20773249/javafx-htmleditor-doesnt-take-all-free-size-on-the-container did actually help :-)

**Comment by ThomasDaheim** [comment]
Works after some struggling. Will create a pull request for "Minor enhancements" so that it can be tested.

**Comment by ThomasDaheim** [comment]
Could you please test if that works as expected?

**Comment by caco3** [comment]
Working as expected.
Thank you very much!
