### ISSUE TITLE
Support key presses

### ISSUE THREAD

**Issue by caco3** [ThomasDaheim/ownNoteEditor#41]
It would be cool if the tool would support key shortcuts, like CTRL-S to save the note.

**Comment by ThomasDaheim** [comment]
Works after some struggling. Will create a pull request for "Minor enhancements" so that it can be tested.

**Comment by ThomasDaheim** [comment]
Could you please test if that works as expected?

**Comment by caco3** [comment]
I like the Ctrl-N and Ctrl-S (and it works as expected).
How ever I think Ctrl-D is very dangerous! There should be at least a confirmation dialogue.

**Comment by caco3** [comment]
But to keep it simple, you also could disable Ctrl-D. IMHO, deleting a note is not a daily action and therefore doesn't really need a shortcut.

**Comment by ThomasDaheim** [comment]
OK, I have removed the CTRL+D short cut
