### ISSUE TITLE
Sort of "Modified" column sorted by string value, not real date/time value

### ISSUE THREAD

**Issue by aviret** [ThomasDaheim/ownNoteEditor#42]
Hello,

When I sort my the column Modified, it's not easy to get the last modified notes (the sort is done by the string value).

So I add a new column (which should be invisible) to sort by real date/time value:

![sortbydatetime](https://cloud.githubusercontent.com/assets/12494348/15389639/385792ac-1db8-11e6-8d29-18ea111eae8f.png)

Do you plan to change the sort function of this column Modified ?

Greetings

**Comment by ThomasDaheim** [comment]
I have added a comparator similar to your approach from #43

**Comment by ThomasDaheim** [comment]
Works after some struggling. Will create a pull request for "Minor enhancements" so that it can be tested.

**Comment by ThomasDaheim** [comment]
Could you please test if that works as expected?

**Comment by aviret** [comment]
Thanks
