### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by tessus** [ThomasDaheim/ownNoteEditor#6]
I get the following error when trying to run it with `./gradlew run`:

`Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain`

**Comment by madmas** [comment]
@tessus what environment do you try to run it with? OS, Java version, etc?

**Comment by tessus** [comment]
Mac OS X 10.11.1

```
$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

Please let me know, if you need any other info.

**Comment by couturierc** [comment]
Same issue :-) 
(and exact same config)

**Comment by madmas** [comment]
Hi, sorry, the wrapper jar was missing, with the changes from the PR, it's working. feel free to validate by using the branch ;-)

**Comment by tessus** [comment]
@madmas which branch? you created a pull request from one of your local branches.

You either have to merge your own pull request or create a branch we can use as well. :-)

**Comment by madmas** [comment]
hi, 
the PR is not for a local branch, it's from the forked repository as usual ;-)

the PR is open and needs to be accepted by @ThomasDaheim ;-)
until then, you can check it out from my fork repository and give it a try

**Comment by tessus** [comment]
@madmas sorry, my bad. for some reason I thought you were the owner of this repo. Argh, the weekend was too exhausting...

ok, your fix works. Thanks.

**Comment by ThomasDaheim** [comment]
91efee9 merged
